array_api_compat/common/_aliases.py, array_api_compat/common/_linalg.py, array_api_compat/cupy/_aliases.py, array_api_compat/numpy/_aliases.py
Also make the basic rename functions just aliases instead of wrapper aliases, so that they are still ufuncs.
=> Pass keyword arguments through in the aliases

array_api_compat/common/_helpers.py, tests/test_get_namespace.py
This PR enables `torch` to be returned by `get_namespace`.
=> Adds pytorch to get_namespace

array_api_compat/common/_helpers.py, tests/test_get_namespace.py
This PR enables `get_namespace` to return the Array API namespace if the input already adapts the Array API standard.
=> Enables get_namespace to return namespace when input adopts Array API spec

array_api_compat/common/_aliases.py, array_api_compat/cupy/_aliases.py, array_api_compat/numpy/_aliases.py, array_api_compat/torch/_aliases.py, tests/_helpers.py, tests/test_array_namespace.py, tests/test_isdtype.py
Fixes #27 
I've added some rudimentary testing here in lieu of test suite support, and also testing that the implementation works with some non-spec dtypes.
=> Implement isdtype()

.github/workflows/array-api-tests-numpy-1-21.yml, .github/workflows/array-api-tests-numpy.yml, array_api_compat/torch/linalg.py, numpy-1-21-xfails.txt, torch-xfails.txt
Mostly minor stuff, like incorrect type promotion or some functions not supporting integer dtypes.
=> More fixes for torch linalg extension

array_api_compat/common/_helpers.py, tests/test_common.py
* allow `to_device(x, "cpu")` for CuPy--this makes it easier to write portable unit tests where the
expected value is on the host (a NumPy array)
* otherwise, you can end up writing different shims in downstream libraries to move the array-like back to the host (`.get()` for CuPy...); if CuPy conforms to the standard, we shouldn't need this shim long-term
=> ENH: support CuPy to_device "cpu"

setup.py
* Add requires-python metadata through the addition of setuptools's python_requires in setup.py.
- c.f. https://peps.python.org/pep-0621/#requires-python
- Set minimum required python to 3.8 as Python 3.7 is EOL as of 2023-06-27.
c.f. https://devguide.python.org/versions/#unsupported-versions
* The addition of requires-python is to provide guards to keep older CPython versions from installing releases that could contain unrunnable code.
c.f. https://github.com/tensorflow/probability/pull/1724
Python 3.8 is also the lower bound on versions tested in CI.
https://github.com/data-apis/array-api-compat/blob/ae7aa8efe660e75bd4f7605dd4f5fddcc4bf34d9/.github/workflows/tests.yml#L6-L8
=> MNT: Add requires-python metadata

array_api_compat/torch/_aliases.py
=> Fix the torch.take() wrapper to make axis optional for ndim = 1

array_api_compat/torch/_aliases.py
Reference comment: https://github.com/scipy/scipy/pull/19051#issuecomment-1699295300 @rgommers 
Expected behaviour: `array_api_compat.torch.result_type` carries out cross-kind promotion like `torch.result_type`.
Observed behaviour:
```python
In [1]: import torch
In [2]: t = torch.tensor([[0, 2], [1, 1], [2, 0]]).T
In [3]: from array_api_compat import array_namespace
In [4]: xp = array_namespace(t)
In [5]: xp.result_type(t, xp.float64)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 1
----> 1 xp.result_type(t, xp.float64)
File ~/dev/array-api-compat/array_api_compat/torch/_aliases.py:136, in result_type(*arrays_and_dtypes)
131     return _promotion_table[xdt, ydt]
133 # …
```
=> BUG: fix `torch.result_type` cross-kind promotion

.github/dependabot.yml, .github/workflows/publish-package.yml
Resolves #50 
Use the OpenID Connect (OIDC) standard to publish to PyPI and TestPyPI using PyPI's "Trusted Publisher" implementation to publish without using API tokens stored as GitHub Actions secrets. Use an optional GitHub Actions environment to further restrict publishing to selected branches for additional security.
- c.f. https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
- c.f. https://docs.pypi.org/trusted-publishers/
=> CI: Add publishing to PyPI and TestPyPI with trusted publishers

.github/workflows/publish-package.yml
As the tag events that trigger workflows are not prefixed by 'v' but instead just use SemVer numbers the GitHub Actions `startsWith` function can only check if a tag has been pushed, as `startsWith` does not support regex.
- c.f. https://docs.github.com/en/actions/learn-github-actions/expressions#startswith
Amends PR #51 (c.f. https://github.com/data-apis/array-api-compat/pull/51/files#r1322311388).
=> CI: Fix tag serach value for TestPyPI publishing

array_api_compat/common/_linalg.py
* this function moved from NumPy core to the public API in recent NumPy builds, and is causing
SciPy CI failures here:
https://github.com/scipy/scipy/actions/runs/6555137521/job/17803175138?pr=19402
* normally I'd use PEP440 for this (either vendored or through the appropriate PyPA lib) but maybe you'd prefer to cheat like this on major version vs. more infrastructure?
=> MAINT: NumPy normalize_axis_tuple

array_api_compat/common/_helpers.py, tests/test_array_namespace.py
=> ENH: disallow passing array-like to array_namespace

array_api_compat/common/_linalg.py
=> BUG: common: fix cholesky upper decomp for complex dtypes

README.md, array_api_compat/__init__.py, array_api_compat/common/_aliases.py
=> MAINT: replace `numpy.array_api` references with `array_api_strict`

cupy-skips.txt, cupy-xfails.txt
This requires #96 and https://github.com/data-apis/array-api-tests/pull/237 for cupy tests to fully pass.
=> Update cupy skips and xfails for latest linalg tests

.github/workflows/array-api-tests.yml, numpy-1-21-xfails.txt
This is needed until https://github.com/data-apis/array-api-tests/issues/238 is fixed.
=> Temporarily pin hypothesis on CI

array_api_compat/common/_helpers.py
Not sure if a warning is the best option here. The returned namespace is 2022.12 compliant, and that is also 2021.12 compliant (except for a few minor things). I don't think it's worth trying to support both, unless someone has a real use-case.
=> Update the api_version check to allow 2022.12 and warn on 2021.12

array_api_compat/torch/_aliases.py, numpy-1-21-xfails.txt
=> Fix torch.std() when correction is an integer

.github/workflows/publish-package.yml
Otherwise this build "fails" on main leading to a bunch of annoying failed actions checks.
=> Only run the publish to pypi build on tags

.github/workflows/array-api-tests.yml
This reverts commit 02059d0d8f025724c08ff757baa6b48a579651ea.
This should no longer be necessary with the latest changes to array-api-tests.
=> Remove hypothesis pin

.github/workflows/docs-deploy.yml
We have to use dawidd6/action-download-artifact to download artifacts from another workflow.
=> Fix docs deploy build

array_api_compat/common/_helpers.py, array_api_compat/numpy/_aliases.py, numpy-dev-xfails.txt, tests/_helpers.py, tests/test_array_namespace.py, tests/test_no_dependencies.py, torch-xfails.txt
This also adds a `use_compat` flag to `array_namespace`. If None, it does the default behavior. If True or False it forces the use or
non-use of the compat wrapper.
Tests will fail here until https://github.com/data-apis/array-api-strict/pull/24 is released.
=> Don't wrap NumPy 2.0 at all

array_api_compat/__init__.py, docs/changelog.md, docs/index.md, test_cupy.sh
I still need to test cupy so I don't know if I will get this out now or if it will need to wait. There is nothing critical in this release.
=> 1.6 release

array_api_compat/common/_helpers.py, tests/test_array_namespace.py
See https://github.com/google/jax/issues/20620.
=> Ensure that Jax float0 array is recognized

.github/workflows/tests.yml, README.md, array_api_compat/common/_helpers.py, requirements-dev.txt
Closes https://github.com/data-apis/array-api-compat/issues/150.
=> Add ndonnx

array_api_compat/common/_helpers.py, tests/test_array_namespace.py
=> BUG: fix `array_namespace` for NumPy scalars

array_api_compat/common/_helpers.py, docs/index.md, tests/_helpers.py, tests/test_array_namespace.py
As of https://github.com/google/jax/pull/22818, `jax.numpy` supports the array API directly, and `jax.experimental.array_api` is deprecated. This change will ensure that `array_api_compat` works correctly with future JAX releases.
=> Future-proof JAX array API import

.github/workflows/tests.yml, array_api_compat/common/_helpers.py, tests/_helpers.py
NumPy 2.0 and 2.1 both have some incompatibilities with the array API (see
#167 and #164).
Closes #168.
=> Re-enable wrapping unconditionally for NumPy

array_api_compat/torch/_aliases.py
torch.conj sets the conjugation bit, which breaks other libraries.
Fixes #173.
=> Use conj_physical for torch.conj

numpy-dev-xfails.txt
Hi @asmeurer,
I think that `numpy-dev-xfails.txt` file is outdated. For some test I see in logs:
```
/home/runner/work/array-api-compat/array-api-compat/array-api-tests/conftest.py:262: UserWarning: 19 ids in xfails file don't match any collected tests: 
```
=> MNT: Update `numpy-dev-xfails.txt`

array_api_compat/common/_helpers.py, docs/helper-functions.rst, tests/test_common.py, tests/test_vendoring.py, vendor_test/uses_cupy.py, vendor_test/uses_dask.py, vendor_test/uses_numpy.py, vendor_test/uses_torch.py
=> add `is_*_namespace` helper functions

array_api_compat/common/_aliases.py, array_api_compat/cupy/_aliases.py, array_api_compat/dask/array/_aliases.py, array_api_compat/numpy/_aliases.py, torch-xfails.txt
=> Add a wrapper for sign for NumPy-likes

array_api_compat/common/_helpers.py, tests/test_array_namespace.py
They are just ignored. This makes array_namespace easier to use for functions that accept either arrays or scalars.
I'm not sure if I should have this behavior by default, or if it should be enabled by a flag.
=> Allow Python scalars in array_namespace

array_api_compat/common/_helpers.py
The check for Python scalars needed to be moved to the end since NumPy scalars subclass the Python scalar types.
=> Fix array_namespace on numpy scalars

array_api_compat/common/_aliases.py
Note that PyTorch uses its own vecdot directly for complex inputs,, which already does conjugation.
This is currently untested by the test suite (data-apis/array-api-tests#312)
Fixes #200.
=> Conjugate the first argument in vecdot

array_api_compat/dask/array/_aliases.py, dask-skips.txt, tests/test_common.py
=> BUG: dask.array: asarray(..., copy=None) copies in dask==2024.12

array_api_compat/common/_helpers.py, tests/test_common.py
Fix bug where plain numpy objects e.g. np.int64(0) would take cupy-specific code paths.
This is a blocker for implementing `at` function in array-api-extra.
=> BUG: cp.generic is an alias for np.generic

array_api_compat/__init__.py
This is needed to work around https://github.com/prefix-dev/pixi/issues/2677.
Without this we can't build array-api-extra against array-api-compat git tip: https://github.com/data-apis/array-api-extra/pull/53#discussion_r1876022501
=> Bump version to 1.10.0.dev0

array_api_compat/__init__.py, array_api_compat/common/_helpers.py, docs/helper-functions.rst, tests/test_common.py
New public function `is_writeable_array`, which introduce transparent support for read-only backends such as JAX (but more may be added in the future).
[EDIT] this PR also implemented an `at` function, mocking the syntax of JAX's omonymous method.
This function will be proposed in array-api-extra instead.
=> ENH: Test for read-only arrays

array_api_compat/common/_helpers.py, tests/test_common.py
dask arrays of unknown shape return NaN in their `.size` and `.shape` properties. This was chosen a long time before the Array API standard existed, but alas diverges from the array API standard itself:
- https://data-apis.org/array-api/latest/API_specification/generated/array_api.array.size.html
- https://data-apis.org/array-api/latest/API_specification/generated/array_api.array.shape.html
ndonnx, another library which can have arrays of unknown shape, uses None instead.
This PR changes the `size()` function to make dask conform to the standard and adds units tests which were previously missing.
**Q:** Should we add a `shape()` function to cover for Dask's `.shape` property non-standard behaviour?
=> ENH: size() to return None on dask instead of nan

array_api_compat/common/_helpers.py, docs/helper-functions.rst, tests/test_common.py
=> ENH: is_lazy_array()

array_api_compat/dask/array/_aliases.py, tests/test_common.py
dask.array.astype doesn't respect copy=True, so we should copy manually.
=> BUG: astype(..., copy=True) doesn't copy on dask

array_api_compat/common/_helpers.py, docs/supported-array-libraries.md, tests/_helpers.py, tests/test_all.py, tests/test_array_namespace.py, tests/test_common.py
- Add array-api-strict and sparse to several parameterized tests
- Add array-api-strict to the documentation
- Detect and xfail more bugs in cross-library `asarray()`
- Follow-up: #232 
**Q:**  (out of scope) shouldn't we add an `is_array_api_strict_array` function, to match `is_array_api_strict_namespace`?
=> TST: run parameterized tests on more libraries

array_api_compat/common/_aliases.py, array_api_compat/cupy/_aliases.py, array_api_compat/dask/array/_aliases.py, array_api_compat/numpy/_aliases.py, array_api_compat/torch/_aliases.py, cupy-xfails.txt, dask-xfails.txt, numpy-1-21-xfails.txt, numpy-1-26-xfails.txt, numpy-dev-xfails.txt, numpy-xfails.txt, torch-xfails.txt
=> ENH: astype: add device kwarg

array_api_compat/common/_helpers.py, tests/test_array_namespace.py, tests/test_common.py, tests/test_jax.py
- Work around https://github.com/jax-ml/jax/issues/26000 on all versions of JAX
- Fix `to_device` on JAX < 0.4.31 inside jax.jit
=> BUG: `.device` attribute inside `jax.jit`

array_api_compat/dask/array/_aliases.py, dask-xfails.txt, tests/test_dask.py
Crude implementation of `sort` and `argsort` for dask.array, which is functionally correct but can be extremely memory and network-intensive.
A better solution would be to implement these two functions in dask.array itself, on top of the shuffle subsystem which is already used for `dask.dataframe.DataFrame.sort_values`.
FYI @fjetter @phofl @hendrikmakait
=> ENH: Dask: `sort` and `argsort`

dask-xfails.txt
https://github.com/dask/dask/issues/11706
Closes https://github.com/data-apis/array-api-tests/issues/338
Also clean up a wealth of XPASS
=> TST: da.arange fails for args near 2**63

array_api_compat/common/_helpers.py, docs/supported-array-libraries.md, tests/_helpers.py, tests/test_array_namespace.py, tests/test_common.py
- Add support to ndonnx in device() and to_device().
- Add ndonnx to parameterized tests
- Add ndonnx to the documentation
- Adds key use cases to #228
- Adds key use cases to #231
=> ENH: ndonnx device() support; TST: better ndonnx test coverage

array_api_compat/common/_fft.py, array_api_compat/common/_typing.py
A companion to https://github.com/data-apis/array-api/pull/885/ [this PR is a draft until the spec PR lands]
=> ENH: add dtype argument to fft.{fftfreq,rfftfreq}

array_api_compat/common/_helpers.py, array_api_compat/common/_typing.py, setup.py
This appears to be the only missing type annotation in the project.
=> Annotate array_namespace and add py.typed

tests/_helpers.py
Crucially, without this it's impossible to run on numpy 2.2, as sparse pins it to <=2.0
=> TST: run tests without all libraries installed

.github/workflows/array-api-tests-dask.yml, .github/workflows/array-api-tests.yml, dask-skips.txt, dask-xfails.txt
Dask is running on 5 cases per test, causing it to be extremely flaky.
~~This PR brings it back in line with other libraries to 200.~~
This PR tweaks xfails and skips after running locally on 2000 examples and adds some commentary.
=> TST: dask tests are extremely flaky

array_api_compat/cupy/_aliases.py, array_api_compat/dask/array/_aliases.py, array_api_compat/numpy/_aliases.py, array_api_compat/torch/_aliases.py
cross-ref https://github.com/data-apis/array-api-tests/pull/347
=> BUG: fix count_nonzero

array_api_compat/common/_aliases.py
This PR makes `clip` no longer crash when `x` has a floating point dtype and `min` and/or `max` are Python `int`s.
```python
import array_api_compat.numpy as xp
xp.clip(xp.asarray(0.0), 0, 1)  # <- this used to crash
```
The [Array API for `clip` states that behavior is unspecified if `x`and either `min` or `max` have different data type kinds](https://data-apis.org/array-api/2024.12/API_specification/generated/array_api.clip.html), but I think the change in this PR makes it behave more like what one might expect. [This change also makes the code more similar to NumPy's handling of Python `int`s in `clip`.](https://github.com/numpy/numpy/blob/main/numpy/_core/_methods.py#L100)
This is my first PR for this repo, hopefully I got it right :) Let me know if I should add anything else.
The …
=> Fix clipping float dtypes when either min or max are Python ints

torch-xfails.txt
Update the xfail listing with functions from https://github.com/data-apis/array-api-tests/pull/348
=> add torch xfails for scalars in binary functions

array_api_compat/torch/_aliases.py, tests/test_all.py, tests/test_torch.py
fixes gh-273,fixes gh-274
cross-ref https://github.com/data-apis/array-api-tests/pull/349 which adds tests.
=> BUG: torch: fix `result_type` with python scalars

cupy-xfails.txt
CuPy 13.x follows NumPy 1.x without "weak scalars". In NumPy `result_type(int32, uint8, 1) != result_type(int32, uint8)` has been fixed in 2.x (or 1.x with set_promotion_state("weak"), so hopefully CuPy 14.x follows the suite, when released.
Until then, just xfail the test.
=> Add a CuPy xfail

array_api_compat/common/_aliases.py, array_api_compat/common/_fft.py, array_api_compat/common/_helpers.py, array_api_compat/common/_linalg.py, array_api_compat/common/_typing.py, array_api_compat/cupy/_aliases.py, array_api_compat/cupy/_typing.py, array_api_compat/dask/array/_aliases.py, array_api_compat/dask/array/fft.py, array_api_compat/dask/array/linalg.py, array_api_compat/numpy/_aliases.py, array_api_compat/numpy/_typing.py, array_api_compat/torch/_aliases.py, array_api_compat/torch/_typing.py, array_api_compat/torch/fft.py, array_api_compat/torch/linalg.py, setup.py, tests/test_all.py
Review all type annotations.
- dtypes were called a mix of `DType` and `Dtype`. I picked `DType` in accordance with `numpy.typing`.
- arrays were called a mix of `Array`, `ndarray`, or `array`. I picked `Array` as it is more idiomatic.
- Added Namespace annotation
- Removed many `TYPE_CHECKING` guards, which were doing nothing but reduce readability (performance impact at runtime is absolutely inconsequential)
- Add `py.typed`. Note that this will typically not work for `array_api_compat.<namespace>.` modules as they are typically pulled in by `array_namespace`, so for most people it is exclusively about `array_api_compat.common._helpers`.
- Add type checkers to CI
- Make `common._typing` public. This will be in a later PR.
=> TYP: Type annotations overhaul, part 1

array_api_compat/common/_aliases.py, array_api_compat/cupy/_aliases.py, array_api_compat/dask/array/_aliases.py, array_api_compat/numpy/_aliases.py, array_api_compat/torch/_aliases.py, array_api_compat/torch/linalg.py
Follow-up to #257, reverting leftover controversial changes re. python scalar data types (see discussion on the other PR).
@ev-br
=> TYP: Type annotations overhaul, part 2

array_api_compat/torch/_aliases.py, array_api_compat/torch/_typing.py
+ Workaround to https://github.com/pytorch/pytorch/issues/150199
+ Also fixes device propagation in `prod`, `sum`, `any` and `all`, which had the same issue induced by array-api-compat
=> BUG: `torch.asarray` device propagation

array_api_compat/common/_aliases.py, array_api_compat/cupy/_aliases.py, array_api_compat/dask/array/_aliases.py, array_api_compat/numpy/_aliases.py, array_api_compat/torch/_aliases.py, cupy-xfails.txt, dask-xfails.txt, numpy-1-21-xfails.txt, numpy-1-26-xfails.txt, numpy-dev-xfails.txt, numpy-xfails.txt, torch-xfails.txt
- Support for array argument in iinfo/finfo
- Pass tests on https://github.com/data-apis/array-api-tests/pull/358
=> ENH: wrap iinfo/finfo

array_api_compat/common/_helpers.py, array_api_compat/dask/array/_aliases.py, array_api_compat/numpy/_aliases.py
Salvaged from #293.
- Validate `device` keyword in `array_api_compat.numpy.astype`
- Validate `device` keyword in all Dask functions
=> MAINT: validate device on numpy and dask

array_api_compat/common/_linalg.py, array_api_compat/cupy/__init__.py, array_api_compat/dask/array/__init__.py, array_api_compat/numpy/__init__.py, array_api_compat/numpy/_aliases.py, array_api_compat/torch/__init__.py, tests/test_common.py
Remove helper functions from wrapped array namespaces.
This was introduced when the numpy namespace was split from the helpers in 2022 (b3a12d92e840be6ef0f87f568d68a4f58b55c7e7).
This PR prompted by a collision between `array_api_compat.device` and `torch.device`.
Re. deprecation layer: unsure if we need one? This was never advertised in the documentation.
=> BUG: Don't import helpers in namespaces

array_api_compat/common/_aliases.py, array_api_compat/cupy/_info.py, array_api_compat/dask/array/_info.py, array_api_compat/numpy/_info.py, array_api_compat/torch/_info.py
- Clarify `__array_namespace_info__().default_device()` output.
Read controversy at https://github.com/data-apis/array-api/issues/835.
- Assorted minor tweaks to the docstrings of the `_info` modules
=> MAINT: `__array_namespace_info__` docstrings tweaks

array_api_compat/torch/_aliases.py
Salvaged from #298
- Simplify dtype promotion table
- Change `sum(x, axis=(), dtype=x.dtype)` and `prod` with the same parameters, which were previously returning `x` itself, to return a deep copy instead. While this is not part of the Array API, it's what both numpy an base torch do, and probably the most healthy thing to do xref https://data-apis.org/array-api/latest/design_topics/copies_views_and_mutation.html.
Discussion here: https://github.com/data-apis/array-api/issues/921
=> MAINT: simplify `torch` dtype promotion

torch-xfails.txt
a companion to https://github.com/data-apis/array-api-tests/pull/366
=> TST: skip testing nextafter with scalars on torch

array_api_compat/common/_linalg.py, array_api_compat/common/_typing.py, array_api_compat/torch/linalg.py
=> TYP: reject `bool` in the `ord` params of `vector_norm` and `matrix_norm`

array_api_compat/common/_aliases.py, array_api_compat/cupy/_aliases.py, array_api_compat/numpy/_aliases.py, dask-xfails.txt
cross-ref https://github.com/data-apis/array-api-tests/pull/367
=> BUG: take_along_axis: numpy requires an axis

array_api_compat/torch/_aliases.py, tests/test_torch.py
As of version 2.6, torch defaults to indexing='ij', and is planning to transition to 'xy' at some point. When it does, we'll be able to drop our wrapper.
cross-ref https://github.com/pytorch/pytorch/issues/50276 for torch-specific details.
One other difference from the spec is that pytorch version returns a tuple of arrays, which matches numpy but deviates from jax or cupy, cross-ref https://github.com/data-apis/array-api/issues/938
=> BUG: torch: meshgrid defaults to indexing="xy"

array_api_compat/numpy/__init__.py
#288 accidentally re-added lines (I assume after a bad merge from main) that were recently deleted in #302.
@ev-br it would be good to have this in the release.
=> MAINT: don't import helpers in numpy namespace

array_api_compat/dask/array/_aliases.py, tests/test_common.py
- Partially fixes #324
- Dask now will raise `ValueError` instead of `NotImplementedError` when it fails `asarray(..., copy=False)`.
- Align test to reflect changes in #314
=> TST: revisit test for `asarray` `copy=` parameter

tests/test_cupy.py
Fix `to_device` test for cupy when there are multiple devices.
UNTESTED, as I don't have multiple GPUs to try this on.
Partially fixes #324.
=> TST: fix cupy `to_device` test on multiple devices

.github/workflows/tests.yml, tests/test_array_namespace.py, tests/test_common.py
split off gh-333
This is pure maintenance of the Tests CI job:
- install torch/array_api_strict on numpy < 2, so that cross-library tests are run and not skipped
- filter out some warnings noise from older versions of the spec
=> Install all libraries in the Test CI job
